name: airflow_ci

on: [push]
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]


jobs:
  airflow_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create airflow env
        run: make setup
      - name: Run tests
        run: make test
      - name: Run test cov
        run: make test_cov
      - name: Run dag test
        run: make dag_test
      - name: Down airflow env
        run: down
  